name: infinite_pagination
description: Truly infinite list helper, provider fixed memory consumption.
version: 0.0.3
homepage: https://github.com/pedia/infinite_pagination

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false